
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  EMPLOYEE: 'EMPLOYEE',
  TEAM_LEAD: 'TEAM_LEAD',
  DEPT_HEAD: 'DEPT_HEAD',
  HR_ADMIN: 'HR_ADMIN',
  TENANT_ADMIN: 'TENANT_ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]
